# Site settings
title: sirisha rambhatla -:-     
email: rambh002@umn.edu
description: > # this means to ignore newlines until "baseurl:"
 Hello World!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://srambhatla.github.io/" # the base hostname & protocol for your site
twitter_username: siri_r
github_username:  srambhatla
highlighter: rouge
# Build settings
markdown: kramdown
